spring.application.name=manwhaverse
spring.datasource.url=jdbc:sqlite:mangadb.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8081
